load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "HandyJSON",
    module_name = "HandyJSON",
    srcs = glob([ 	"Sources/**/*.swift"]),
    visibility = ["//visibility:public"]
)
