
exports_files([
	"Widget.mobileprovision",	"WatchExtension.mobileprovision",	"watchkitapp.mobileprovision",	"SiriIntents.mobileprovision",	"Share.mobileprovision",	"Notification_Service.mobileprovision",	"Notification_Content.mobileprovision",	"BroadcastUpload.mobileprovision",	"wev_profile.mobileprovision",
])
