
exports_files([
	"Widget.mobileprovision",	"Share.mobileprovision",	"Notification_Service.mobileprovision",	"Notification_Content.mobileprovision",	"wev_profile_adhoc.mobileprovision",	"SiriIntents.mobileprovision",	"BroadcastUpload.mobileprovision",
	"watchkitapp.mobileprovision",
	"WatchExtension.mobileprovision",
])
